### ISSUE TITLE
Stream not found

### ISSUE THREAD

**Issue by wilstoff** [synadia-labs/eventually-consistent-virtual-global-stream#4]
I've translated the configuration as best i see to our 3 cluster (with 3 nodes each) environment and i'm having some inconsistencies with matching up the eventual consistency topics.   In our C# client we're getting a stream not found error message when subscribing to one of these streams with an appended on topic ie (stream name configured is js_test_bill_2, subscribing on topic js_test_bill_2.abc123).
NATS.Client.JetStream.NATSJetStreamException : stream not found [10059]
   at NATS.Client.JetStream.ApiResponse.ThrowOnHasError()
   at NATS.Client.JetStream.ApiResponse.InitJson(String json, Boolean throwOnError)
   at NATS.Client.JetStream.ApiResponse..ctor(Msg msg, Boolean throwOnError, Boolean ignoreMessage)
   at NATS.Client.JetStream.ConsumerInfo..ctor(Msg msg, Boolean throwOnError)
   at NATS.Client.JetStream.JetStreamBase.CreateConsumerInternal(String streamName, ConsumerConfiguration config, ConsumerCreateRequestAction ccrAction)
   at NATS.Client.JetStream.JetStream.CreateSubscription(String userSubscribeSubject, PushSubscribeOptions pushSubscribeOptions, PullSubscribeOptions pullSubscribeOptions, String queueName, EventHandler`1 userHandler, Boolean autoAck, PullMessageManager pmmInstance)
   at NATS.Client.JetStream.JetStream.PushSubscribeAsync(String subject, EventHandler`1 handler, Boolean autoAck, PushSubscribeOptions options)

I can also recreate something similar with the cli, where subscribing doesn't get back any messages, but requesting a new message does seem to be responded to by the appropriate stream:

```
root@chivmdevnats001:~  # nats --context riv sub js_bill_test_2.abc123
16:45:13 Subscribing on js_bill_test_2.abc123
root@chivmdevnats002:~  # nats --context riv req js_bill_test_2.abc123 'Hi3'
16:46:01 Sending request on "js_bill_test_2.abc123"
16:46:01 Received with rtt 1.005941ms
{"stream":"js_bill_test_2-write-riv", "seq":7}
```

Nothing seems to show up.   Below is how i have configured everything and can follow up with any more configuration that may be odd.  I have a feeling that there is some other internal JS api that has changed with different versions and this repo is stale on what is required for this configuration to work.   I have reloaded the nats server configuration multiple times.

Nats server version:  nats-server --version
nats-server: v2.10.14
C# API version (can't go to async): 1.1.5
Nats cli version: 0.1.4

Nats1.cfg (similar config for other data centers)
```
listen: 10.10.162.24:4222

logtime: true
log_file: "/var/log/nats/nats1.log"
server_name: riv_1
http_port: 8222
debug: False
trace: False
max_pending: 268435456
max_payload: 10000000
write_deadline: 5s

jetstream: {
  store_dir: "/var/cache/nats_js1"
  max_memory_store: 1GB
  max_file_store: 100GB
}
cluster: {
  listen: 10.10.162.24:5222
  routes: [nats-route://chivmdevnats001:5222, nats-route://chivmdevnats002:5222, nats-route://chivmdevnats003:5222]
  name: riv
}
gateway: {
  name: riv
  listen: 10.10.162.24:7222
  reject_unknown: true
  gateways: [{'name': 'riv', 'urls': ['nats://chivmdevnats001:7222', 'nats://chivmdevnats002:7222', 'nats://chivmdevnats003:7222']}, {'name': 'eqx', 'urls': ['nats://eqxsrvdev022:7222', 'nats://eqxsrvdev022:7223', 'nats://eqxsrvdev022:7224']}, {'name': 'ny4', 'urls': ['nats://ny4srvdev023:7222', 'nats://ny4srvdev023:7223', 'nats://ny4srvdev023:7224']}]

}
include ./stream_mappings_1.cfg
```

mappings
```
mappings = {
"js_bill_test_2.>":[
    {destination:"js_bill_test_2.riv.>", weight: 100%, cluster: "riv"},
    {destination:"js_bill_test_2.eqx.>", weight: 100%, cluster: "eqx"},
    {destination:"js_bill_test_2.ny4.>", weight: 100%, cluster: "ny4"},
  ],
  "$JS.API.STREAM.INFO.js_bill_test_2":[
    {destination:"$JS.API.STREAM.INFO.js_bill_test_2-read-riv", weight: 100%, cluster: "riv"},
    {destination:"$JS.API.STREAM.INFO.js_bill_test_2-read-eqx", weight: 100%, cluster: "eqx"},
    {destination:"$JS.API.STREAM.INFO.js_bill_test_2-read-ny4", weight: 100%, cluster: "ny4"},
  ],
  "$JS.API.CONSUMER.DURABLE.CREATE.js_bill_test_2.*":[
    {destination:"$JS.API.CONSUMER.DURABLE.CREATE.js_bill_test_2-read-riv.{{wildcard(1)}}", weight: 100%, cluster: "riv"},
    {destination:"$JS.API.CONSUMER.DURABLE.CREATE.js_bill_test_2-read-eqx.{{wildcard(1)}}", weight: 100%, cluster: "eqx"},
    {destination:"$JS.API.CONSUMER.DURABLE.CREATE.js_bill_test_2-read-ny4.{{wildcard(1)}}", weight: 100%, cluster: "ny4"},
  ],
  "$JS.API.CONSUMER.CREATE.js_bill_test_2.*":[
    {destination:"$JS.API.CONSUMER.CREATE.js_bill_test_2-read-riv.{{wildcard(1)}}", weight: 100%, cluster: "riv"},
    {destination:"$JS.API.CONSUMER.CREATE.js_bill_test_2-read-eqx.{{wildcard(1)}}", weight: 100%, cluster: "eqx"},
    {destination:"$JS.API.CONSUMER.CREATE.js_bill_test_2-read-ny4.{{wildcard(1)}}", weight: 100%, cluster: "ny4"},
  ],
  "$JS.API.STREAM.MSG.GET.js_bill_test_2":[
    {destination:"$JS.API.STREAM.MSG.GET.js_bill_test_2-read-riv", weight: 100%, cluster: "riv"},
    {destination:"$JS.API.STREAM.MSG.GET.js_bill_test_2-read-eqx", weight: 100%, cluster: "eqx"},
    {destination:"$JS.API.STREAM.MSG.GET.js_bill_test_2-read-ny4", weight: 100%, cluster: "ny4"},
  ],
  "$JS.API.STREAM.MSG.DIRECT.js_bill_test_2":[
    {destination:"$JS.API.STREAM.MSG.DIRECT.js_bill_test_2-read-riv", weight: 100%, cluster: "riv"},
    {destination:"$JS.API.STREAM.MSG.DIRECT.js_bill_test_2-read-eqx", weight: 100%, cluster: "eqx"},
    {destination:"$JS.API.STREAM.MSG.DIRECT.js_bill_test_2-read-ny4", weight: 100%, cluster: "ny4"},
  ],
  "$JS.API.STREAM.MSG.DELETE.js_bill_test_2":[
    {destination:"$JS.API.STREAM.MSG.DELETE.js_bill_test_2-read-riv", weight: 100%, cluster: "riv"},
    {destination:"$JS.API.STREAM.MSG.DELETE.js_bill_test_2-read-eqx", weight: 100%, cluster: "eqx"},
    {destination:"$JS.API.STREAM.MSG.DELETE.js_bill_test_2-read-ny4", weight: 100%, cluster: "ny4"},
  ],
  "$JS.API.CONSUMER.MSG.NEXT.js_bill_test_2.*":[
    {destination:"$JS.API.CONSUMER.MSG.NEXT.js_bill_test_2-read-riv.{{wildcard(1)}}", weight: 100%, cluster: "riv"},
    {destination:"$JS.API.CONSUMER.MSG.NEXT.js_bill_test_2-read-eqx.{{wildcard(1)}}", weight: 100%, cluster: "eqx"},
    {destination:"$JS.API.CONSUMER.MSG.NEXT.js_bill_test_2-read-ny4.{{wildcard(1)}}", weight: 100%, cluster: "ny4"},
  ],
  "$JS.ACK.js_bill_test_2.>":[
    {destination:"$JS.ACK.js_bill_test_2-read-riv.>", weight: 100%, cluster: "riv"},
    {destination:"$JS.ACK.js_bill_test_2-read-eqx.>", weight: 100%, cluster: "eqx"},
    {destination:"$JS.ACK.js_bill_test_2-read-ny4.>", weight: 100%, cluster: "ny4"},
  ],
}
```

Read stream created:

```
{
  "name": "js_bill_test_2-read-riv",
  "retention": "limits",
  "max_consumers": 10000,
  "max_msgs_per_subject": -1,
  "max_msgs": 1000000,
  "max_bytes": 1073741824,
  "max_age": 259200000000000,
  "max_msg_size": 8388608,
  "storage": "file",
  "discard": "old",
  "num_replicas": 3,
  "duplicate_window": 120000000000,
  "placement": {
    "cluster": "riv"
  },
  "subject_transform": {
    "src":"js_bill_test_2.*.>",
    "dest":"js_bill_test_2.>"
  },
  "sources": [
    {
      "name": "js_bill_test_2-write-riv",
      "filter_subject": "js_bill_test_2.riv.>"
    },
    {
      "name": "js_bill_test_2-write-eqx",
      "filter_subject": "js_bill_test_2.eqx.>"
    },
    {
      "name": "js_bill_test_2-write-ny4",
      "filter_subject": "js_bill_test_2.ny4.>"
    }
  ],
  "sealed": false,
  "deny_delete": false,
  "deny_purge": false,
  "allow_rollup_hdrs": false,
  "allow_direct": false,
  "mirror_direct": false
}
```

Write stream configuration:

```
{
  "name": "js_bill_test_2-write-riv",
  "subjects": [
    "js_bill_test_2.riv.>"
  ],
  "retention": "limits",
  "max_consumers": 10000,
  "max_msgs_per_subject": -1,
  "max_msgs": 1000000,
  "max_bytes": 1073741824,
  "max_age": 259200000000000,
  "max_msg_size": 8388608,
  "storage": "file",
  "discard": "old",
  "num_replicas": 3,
  "duplicate_window": 120000000000,
  "placement": {
    "cluster": "riv"
  },
  "sealed": false,
  "deny_delete": false,
  "deny_purge": false,
  "allow_rollup_hdrs": false,
  "allow_direct": false,
  "mirror_direct": false
}
```

```
root@chivmdevnats001:nats  # nats --context riv stream info js_bill_test_2
Information for Stream js_bill_test_2-read-riv created 2024-07-30 16:20:27

              Replicas: 3
               Storage: File
     Placement Cluster: riv

Options:

     Subject Transform: js_bill_test_2.*.> to js_bill_test_2.>
             Retention: Limits
       Acknowledgments: true
        Discard Policy: Old
      Duplicate Window: 2m0s
     Allows Msg Delete: true
          Allows Purge: true
        Allows Rollups: false

Limits:

      Maximum Messages: 1,000,000
   Maximum Per Subject: unlimited
         Maximum Bytes: 1.0 GiB
           Maximum Age: 3d0h0m0s
  Maximum Message Size: 8.0 MiB
     Maximum Consumers: 10,000

Replication:

               Sources: js_bill_test_2-write-eqx
                        js_bill_test_2-write-ny4
                        js_bill_test_2-write-riv

Cluster Information:

                  Name: riv
                Leader: riv_1
               Replica: riv_2, current, seen 231ms ago
               Replica: riv_3, current, seen 231ms ago

Source Information:

           Stream Name: js_bill_test_2-write-eqx
        Subject Filter: js_bill_test_2.eqx.>
                   Lag: 0
             Last Seen: 499ms

           Stream Name: js_bill_test_2-write-ny4
        Subject Filter: js_bill_test_2.ny4.>
                   Lag: 0
             Last Seen: 651ms

           Stream Name: js_bill_test_2-write-riv
        Subject Filter: js_bill_test_2.riv.>
                   Lag: 0
             Last Seen: 824ms

State:

              Messages: 8
                 Bytes: 1.1 KiB
        First Sequence: 1 @ 2024-07-30 16:36:15 UTC
         Last Sequence: 8 @ 2024-07-30 16:46:01 UTC
      Active Consumers: 0
    Number of Subjects: 1
```

**Comment by jnmoyne** [comment]
> root@chivmdevnats001:~  # nats --context riv sub js_bill_test_2.abc123
> 16:45:13 Subscribing on js_bill_test_2.abc123

The technique described in the blog and implemented in this repo are only for JetStream, not Core NATS. Meaning that you can create a consumer on the stream `js_bill_test_2` and it will (though subject mapping) actually create a consumer on the read stream (`js_bill_test_2-read`). But you can't just subscribe to `js_bill_test_2.>` that will never see any messages (the messages published by the application on that subject being subject mapped to add a subject token with the local cluster's name (e.g. in cluster 'riv' a message published on `js_bill_test_2.foo` gets transformed to `js_bill_test_2.riv.foo`).

As for your .Net application, you can see from the trace that it's trying to do a consumer info on the stream:
> at NATS.Client.JetStream.ConsumerInfo..ctor(Msg msg, Boolean throwOnError)

However looking at your mappings, there isn't a mapping for the JS API's consumer info calls, which is why the consumer info JS API request sent by the client application (the .Net client library specifically) doesn't get mapped and therefore times out. 

You should add the following to you mappings:
```
  "$JS.API.CONSUMER.INFO.js_bill_test_2.*":[
    {destination:"$JS.API.CONSUMER.INFO.js_bill_test_2-read-riv.{{wildcard(1)}}", weight: 100%, cluster: "riv"},
    {destination:"$JS.API.CONSUMER.INFO.js_bill_test_2-read-eqx.{{wildcard(1)}}", weight: 100%, cluster: "eqx"},
    {destination:"$JS.API.CONSUMER.INFO.js_bill_test_2-read-ny4.{{wildcard(1)}}", weight: 100%, cluster: "ny4"},
  ],
```

(I see that the repo's mapping file does not have a mapping for consumer info, it has now been added)
